stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            tree: false
            timestampable: true
            translatable: false
            loggable: false
            sluggable: true
            sortable: false
