twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_locales: '%app.locales.available%'
    form_themes:
        - 'admin/form_div_layout.html.twig'
